pipeline {
    agent any
    environment {
        APP_NAME = "nodejs-app"
    }
    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }
        stage("Checkout from SCM") {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/AbdessamadKhaoula/gitOps-pipline'
            }
        }
        stage("Update the Deployment Tags") {
            steps {
                sh """
                    cat deployment.yaml
                    sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                    cat deployment.yaml
                """
            }
        }
        stage("Push the Changed Deployment File to GitHub") {
            steps {
                sh """
                    git config --global user.name "AbdessamadKhaoula"
                    git config --global user.email "khaoulaabdessamad2002@gmail.com"
                    git add deployment.yaml
                    git commit -m "Updated Deployment Manifest"
                """
                withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                    sh "git push https://github.com/AbdessamadKhaoula/gitOps-pipline main"
                }
            }
        }
    }
}